name: nutrilog
description: "NutriLog - App de acompanhamento alimentar que conecta clientes e nutricionistas."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  geolocator: ^13.0.1
<<<<<<< HEAD
  intl: ^0.20.2
=======

  # Utilitários de data/localização
  intl: ^0.19.0
>>>>>>> b9bb4d453ad986ded85dd560bd99a21fd56fac98

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
